class WordManager {
  #words = {
    // 5 lettres — Facile
    easy: [
      'ARBRE','AVION','BAGUE','BALLE','BATON','BELLE','BLANC','BOMBE','BOULE','BRAVE',
      'BULLE','CALME','CARTE','CHANT','CHOSE','COEUR','COUPE','CREME','CYCLE','DANSE',
      'DEPOT','DROIT','ECOLE','ECLAT','ELITE','EMAIL','ETANG','EVEIL','FABLE','FERME',
      'FIBRE','FLEUR','FOLIE','FORCE','FORME','FOULE','FRUIT','GALET','GAZON','GEANT',
      'GLOBE','GLACE','GRACE','GRAIN','GRAND','HERBE','HOTEL','IMAGE','JETON','JOUET',
      'LAPIN','LARGE','LASER','LEGER','LIVRE','LOCAL','MAGIE','MARIN','MATIN','MELON',
      'MERCI','METRO','MICRO','MONDE','MORAL','MOYEN','MUSEE','NAPPE','NEIGE','NOBLE',
      'NORME','NUAGE','OCEAN','OLIVE','ORAGE','ORDRE','OUTIL','PACTE','PAUSE','PEINE',
      'PERLE','PIANO','PISTE','PLACE','PLAGE','PLUME','POMME','PORTE','PRISE','PRUNE',
      'RADAR','REGAL','REINE','RONDE','ROUGE','RUCHE','SABRE','SABLE','SAPIN','SCENE'
    ],
    // 6 lettres — Moyen
    medium: [
      'ACTEUR','AGENDA','AIMANT','ANCIEN','AURORE','AVATAR','BALLON','BANANE','BEAUTE','BILLET',
      'BOUTON','BUREAU','CABANE','CAHIER','CANARD','CHAINE','CHALET','CHANCE','CIRQUE','CITRON',
      'CLASSE','CLIENT','COLERE','COMBAT','DANGER','DEBOUT','DEHORS','DELICE','DESTIN','DRAGON',
      'DROITE','ECLAIR','ECRIRE','EGLISE','EMPLOI','ENFANT','ENNEMI','EPOQUE','EQUIPE','ETOILE',
      'FAIBLE','FAMEUX','JARDIN','LAGUNE','MARCHE','MIROIR','NAGEUR','ORANGE','PARTIR','PLAIRE',
      'PLANTE','POLICE','PORTER','PRISON','RAMPER','REFLET','RETOUR','RIDEAU','RIVAGE','SAVEUR',
      'SOLEIL','TALENT','TORCHE','TOUCHE','TRACER','TRESOR','TRISTE','TULIPE','TURBAN','VALISE',
      'VENTRE','VIANDE','VIRAGE','VISAGE','VOLCAN','VOYAGE','VERGER','VENGER','SOURCE','MOULIN'
    ],
    // 7 lettres — Difficile
    hard: [
      'ABSURDE','AFFAIRE','AILERON','ALIMENT','ALLUMER','AMASSER','AMUSANT','ANNONCE','APAISER','ARBUSTE',
      'ARCHIVE','ARDOISE','ARRIVER','ARTISTE','ASSUMER','ATTAQUE','AVANCER','BALANCE','BARAQUE','BIZARRE',
      'BLOQUER','BRILLER','BRIGADE','CABINET','CAPABLE','CAPTURE','CASCADE','CERTAIN','CHANGER','CHEMISE',
      'CHOISIR','CIRCUIT','CLAVIER','CLOISON','COLONNE','COMPTER','CONCERT','CONTENU','COULEUR','COURAGE',
      'CULTURE','DEMANDE','DEPENSE','DESSERT','DOMAINE','ECLATER','ELEGANT','EMBLEME','ENCODER','ENERGIE',
      'EVASION','FAMILLE','FENETRE','GALERIE','HEUREUX','HORIZON','INSPIRE','INSTANT','INVITER','JUSTICE',
      'LANGAGE','LECTURE','LIBERTE','MACHINE','MAXIMUM','MONTAGE','NERVEUX','NOUVEAU','ORIGINE','PALMIER',
      'PARTAGE','PENSION','PLANETE','PLATEAU','PORTAIL','POUVOIR','PREMIER','PRENDRE','PRESENT','PRODUIT',
      'REALISE','RECETTE','RELANCE','REMPART','REPRISE','RESERVE','RIVIERE','ROMANCE','ROYAUME','SAGESSE',
      'SALAIRE','SAUVAGE','SCIENCE','SENTIER','SILENCE','SOCIETE','SOLAIRE','SOMMEIL','SOURIRE','SPECTRE'
    ]
  };

  getRandom(difficulty = 'easy') {
    const list = this.#words[difficulty] ?? this.#words.easy;
    return list[Math.floor(Math.random() * list.length)];
  }
}
